import "./globals.css";
import Header from "./_Header/page";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <link href={"https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css"} rel="stylesheet"
                  integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7"
                  crossOrigin="anonymous"/>
            <link rel="stylesheet" href={"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"}
                  integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
                  crossOrigin="anonymous" referrerPolicy="no-referrer"/>
        </head>
        <body
            data-new-gr-c-s-check-loaded="8.929.0"
            data-gr-ext-installed=""
        >

        <Header/>

        <div className={"container"}>
            {children}
        </div>

        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src={"https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"}
                integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
                crossOrigin="anonymous"></script>
        </body>
        </html>
    );
}
